services:
  nuxt:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: tail -f /dev/null
networks:
  sail:
    driver: bridge
